# Generated by Django 3.2.4 on 2021-08-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_group_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='creator',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
